version: "3.8"

services:
  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: baboon
      POSTGRES_USER: baboon
      POSTGRES_DB: laravel

  elastic:
    image: elasticsearch:5
    restart: on-failure
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=larabon-es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - include_type_name=true
